spring.application.name=Comanda-Digital

# URL de conexão para db4free
spring.datasource.url=jdbc:mysql://db4free.net:3306/mobile40028922

# Usuário e senha do banco
spring.datasource.username=mobile40028922
spring.datasource.password=mobile01

# Configurações JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
